# Generated by Django 4.0.1 on 2024-05-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='profile_pictures'),
        ),
    ]
