# Generated by Django 4.0.1 on 2024-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_profile_country_remove_profile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering')], default='Computer Engineering', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineering')], default='Engineering', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('100 Level', '100 Level'), ('200 Level', '200 Level'), ('300 Level', '300 Level'), ('400 Level', '400 Level'), ('500 Level', '500 Level')], max_length=50),
        ),
    ]
