# Generated by Django 4.2.4 on 2023-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='None', max_length=30, unique=True),
        ),
    ]
