# Generated by Django 4.2.5 on 2023-09-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-30 0:0:0'),
            preserve_default=False,
        ),
    ]
