# Generated by Django 4.2.14 on 2024-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0002_choice_course_department_faculty_question_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(max_length=1000),
        ),
    ]
