# Generated by Django 4.2.14 on 2024-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0003_alter_question_option_1_alter_question_option_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=1000),
        ),
    ]
