# Generated by Django 4.0.1 on 2024-05-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0004_userresponse_course_userresponse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
    ]
