# Generated by Django 4.0.1 on 2024-05-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutdb.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.CharField(choices=[('2021/2022', '2021/2022'), ('2022/2023', '2022/2023')], default='2022/2023', max_length=100),
        ),
    ]
