# Generated by Django 4.0.1 on 2024-05-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0005_remove_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutdb.course'),
        ),
    ]
