# Generated by Django 4.0.1 on 2024-05-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0006_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
