# Generated by Django 4.0.1 on 2024-05-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0006_alter_userresponse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutdb.choice'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutdb.session'),
        ),
    ]
