# Generated by Django 4.0.1 on 2024-05-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0007_alter_userresponse_selected_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutdb.choice'),
        ),
    ]
