# Generated by Django 4.0.1 on 2024-05-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0007_course_code_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='session',
        ),
        migrations.AlterField(
            model_name='course',
            name='code_slug',
            field=models.SlugField(default='gtc-432', max_length=100),
            preserve_default=False,
        ),
    ]
