# Generated by Django 4.0.1 on 2024-05-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutdb', '0008_session_remove_question_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default='20212022', max_length=100),
            preserve_default=False,
        ),
    ]
